# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V
  - pip install pipenv
  - pipenv install --dev

py36:
  image: python:3.6
  stage: test
  script:
    - pipenv run tox -epy36

py37:
  image: python:3.7
  stage: test
  script:
    - pipenv run tox -epy37

py38:
  image: python:3.8
  stage: test
  script:
    - pipenv run tox -epy38
  coverage: '/^TOTAL(?:\s+\d+){4}\s+(\d+\%)$/'

pypy:
  image: pypy:3.6
  stage: test
  script:
    - pypy3 -V
    - pipenv run tox -epypy3
