# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python -V
  - pip install poetry
  - poetry install

py36:
  image: python:3.6
  stage: test
  script:
    - poetry run pip uninstall -y horn-py
    - make clean
    - poetry run pip freeze > r.txt
    - poetry env remove 3.7
    - pip uninstall -y poetry
    - rm pyproject.toml
    - sed -i '1,3d' r.txt
    - sed -i -E '/^poetry.+$/d' r.txt
    - pip install -r r.txt
    - pip install -e .
    - tox -epy36

py37:
  image: python:3.7
  stage: test
  script:
    - poetry run tox -epy37

py38:
  image: python:3.8
  stage: test
  script:
    - poetry run tox -epy38
  coverage: '/^TOTAL.+?(\d+\%)$/'

pypy:
  image: pypy:3.6
  stage: test
  script:
    - pypy3 -V
    - poetry run pip uninstall -y horn-py
    - make clean
    - poetry run pip freeze > r.txt
    - poetry env remove 3.7
    - pip uninstall -y poetry
    - rm pyproject.toml
    - sed -i '1,3d' r.txt
    - sed -i -E '/^poetry.+$/d' r.txt
    - pip install -r r.txt
    - pip install -e .
    - tox -epypy3
