language: python
cache: pip
sudo: false

python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - pypy3

install:
  - pip install codecov
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install
  - echo "$TRAVIS_PYTHON_VERSION"
before_script:
  - poetry about
script:
  - "if [[ $TRAVIS_PYTHON_VERSION == 'pypy3' ]]; then poetry add importlib_resources; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then poetry add importlib_resources; fi"
  - poetry run tox

after_success:
  - codecov
