language: python
cache: pip
sudo: false

python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
  - 3.11
  - pypy3

install:
  - pip install codecov
  - pip install poetry
  - poetry config virtualenvs.create false
  - poetry install
  - echo "$TRAVIS_PYTHON_VERSION"
before_script:
  - poetry about
script:
  - poetry run pytest

after_success:
  - codecov
